### ISSUE TITLE
`dimensions-1.0.1.1` fails to build with GHC 8.10 and up

### ISSUE THREAD

**Issue by andreasabel** [achirkin/fasttensor#33]
``` 
dimensions-1.0.1.1$ cabal build -w ghc-8.10.7
...
src/Numeric/Dim.hs:123:29: error: Not in scope: type variable ‘k’
    |
123 | pattern Dim :: forall (n :: k) . () => KnownDim n => Dim n
    |                             ^
```

**Comment by andreasabel** [comment]
Added`base < 4.14` constraint to `dimensions < 2` packages on Hackage.
